# Generated by Django 5.1.6 on 2025-03-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='level',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
