# Generated by Django 5.1.6 on 2025-03-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0002_remove_grade_group_remove_grade_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
