# Generated by Django 5.1.6 on 2025-03-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='parts',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
