# Generated by Django 5.1.6 on 2025-03-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0009_remove_homework_subject_homework_course'),
        ('app_payments', '0002_remove_payment_parts_delete_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='app_courses.group'),
        ),
    ]
