# Generated by Django 5.1.5 on 2025-02-28 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0003_remove_group_student_count'),
        ('app_users', '0002_department_rename_is_user_user_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cource',
            field=models.ManyToManyField(related_name='student', to='app_courses.course'),
        ),
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='student', to='app_courses.group'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cource', models.ManyToManyField(related_name='t_student', to='app_courses.course')),
                ('group', models.ManyToManyField(related_name='t_student', to='app_courses.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='parent', to='app_users.student'),
        ),
    ]
