# Generated by Django 5.1.5 on 2025-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0003_remove_group_student_count'),
        ('app_users', '0003_student_cource_remove_parent_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='t_student', to='app_courses.group'),
        ),
    ]
