# Generated by Django 5.1.5 on 2025-03-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0003_remove_group_student_count'),
        ('app_users', '0005_alter_teacher_cource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cource',
            field=models.ManyToManyField(blank=True, null=True, related_name='student', to='app_courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='student', to='app_courses.group'),
        ),
    ]
