# Generated by Django 5.1.6 on 2025-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0004_alter_table_finish_time_alter_table_start_time'),
        ('app_users', '0006_alter_student_cource_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cource',
            field=models.ManyToManyField(blank=True, null=True, related_name='c_teacher', to='app_courses.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='t_teacher', to='app_courses.group'),
        ),
    ]
