# Generated by Django 5.1.6 on 2025-03-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0005_remove_group_worker'),
        ('app_users', '0007_alter_teacher_cource_alter_teacher_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_worker',
            new_name='is_teacher',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
