# Generated by Django 5.1.6 on 2025-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0006_group_teacher'),
        ('app_users', '0008_rename_is_worker_user_is_teacher_delete_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='group',
        ),
        migrations.AlterField(
            model_name='student',
            name='cource',
            field=models.ManyToManyField(blank=True, null=True, related_name='c_student', to='app_courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='g_student', to='app_courses.group'),
        ),
    ]
