# Generated by Django 5.1.6 on 2025-03-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_remove_teacher_group_alter_student_cource_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
