# Generated by Django 5.1.6 on 2025-03-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0009_remove_homework_subject_homework_course'),
        ('app_users', '0010_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cource',
            field=models.ManyToManyField(related_name='c_student', to='app_courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='g_student', to='app_courses.group'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cource',
            field=models.ManyToManyField(related_name='c_teacher', to='app_courses.course'),
        ),
    ]
