# Generated by Django 5.1.6 on 2025-03-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0010_alter_group_teacher'),
        ('app_users', '0011_alter_student_cource_alter_student_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='g_student', to='app_courses.group'),
        ),
    ]
