# Generated by Django 5.1.6 on 2025-02-28 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_courses', '0001_initial'),
        ('app_users', '0002_department_rename_is_user_user_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app_users.worker'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app_courses.subject'),
        ),
        migrations.AddField(
            model_name='group',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='app_courses.table'),
        ),
        migrations.AddField(
            model_name='table',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app_courses.tabletype'),
        ),
    ]
