# Generated by Django 5.1.5 on 2025-02-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student_count',
        ),
    ]
