# Generated by Django 5.1.6 on 2025-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0003_remove_group_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='finish_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
