# Generated by Django 5.1.6 on 2025-03-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0004_alter_table_finish_time_alter_table_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='worker',
        ),
    ]
