# Generated by Django 5.1.6 on 2025-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0005_remove_group_worker'),
        ('app_users', '0008_rename_is_worker_user_is_teacher_delete_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='app_users.teacher'),
        ),
    ]
