# Generated by Django 5.1.6 on 2025-03-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0007_alter_group_teacher_homework_homeworksubmission'),
        ('app_users', '0010_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app_courses.homeworksubmission')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_users.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
