# Generated by Django 5.1.6 on 2025-03-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0008_homeworkreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='subject',
        ),
        migrations.AddField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='app_courses.course'),
            preserve_default=False,
        ),
    ]
