# Generated by Django 5.1.6 on 2025-03-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0009_remove_homework_subject_homework_course'),
        ('app_users', '0011_alter_student_cource_alter_student_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='app_users.teacher'),
        ),
    ]
